name: SonarCloud Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build and test
      run: |
        ./mvnw clean verify

    - name: SonarCloud Scan
      run: |
        ./mvnw sonar:sonar \
          -Dsonar.organization=mappyproject \
          -Dsonar.projectKey=Mappyproject_subscriptionservice \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}