name: SonarCloud Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    env:
      EUREKA_HOST: ${{ secrets.EUREKA_HOST }}
      MONGODB_URL: ${{ secrets.MONGODB_URL }}
      MONGODB_NAME: ${{ secrets.MONGODB_NAME }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build and test
      run: |
        echo "Eureka Host: $EUREKA_HOST"
        echo "MongoDB URL: $MONGODB_URL"
        echo "MongoDB Name: $MONGODB_NAME"
        mvn clean verify

    - name: SonarCloud Scan
      run: |
        mvn sonar:sonar \
          -Dsonar.organization=mappyproject \
          -Dsonar.projectKey=Mappyproject_subscriptionservice \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  deployment:
      name: Deployment
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 17
          uses: actions/setup-java@v1
          with:
            java-version: 17
        - name: Build and test
          run: mvn clean install jib:build -Djib.to.auth.username=${{ secrets.DOCKERHUB_USERNAME }} -Djib.to.auth.password=${{ secrets.DOCKERHUB_PASSWORD }}